Repository TopAcademy2022/music-store, pull requests merged in 2024-11, with the labels that each got.

#2 Added project files. Closed #1
  music-store.sln
  music-store/Models/Entities/MusicBand.cs
  music-store/Models/Entities/MusicGenre.cs
  music-store/Models/Entities/MusicPublisher.cs
  music-store/Models/Entities/VinylRecord.cs
  music-store/Services/Interfaces/ADatabaseConnection.cs
  music-store/Services/SqliteConnection.cs
  music-store/music-store.csproj
Labels: enhancement

#12 Added system users. Closed #9
  music-store/Models/Entities/User.cs
  music-store/Services/Interfaces/ADatabaseConnection.cs
  music-store/Services/Interfaces/IUserService.cs
  music-store/Services/UserService.cs
Labels: enhancement

#17 Added method for deleting users. Closed #15
  music-store/Services/Interfaces/IUserService.cs
  music-store/Services/UserService.cs
Labels: enhancement

#13 Added method for adding vinyl records. Closed #3
  music-store/Services/Interfaces/IVinylRecordsService.cs
  music-store/Services/VinylRecordsService.cs
Labels: documentation, enhancement

#22 Added method for adding music bands. Closed #4
  music-store/Services/Interfaces/IMusicBandService.cs
  music-store/Services/MusicBandService.cs
Labels: documentation, enhancement

#21 Added method for adding music genres records. Closed #6
  music-store/Services/Interfaces/IMusicGenereService.cs
  music-store/Services/MusicGenereService.cs
Labels: documentation, enhancement

#26 Added method for adding music publishers. Closed #5
  music-store/Services/Interfaces/IMusicPublisherService.cs
  music-store/Services/MusicPublisherService.cs
Labels: documentation, enhancement

#25 Added method for find vinyl records by name. Closed #23
  music-store/Services/Interfaces/IVinylRecordsService.cs
  music-store/Services/VinylRecordsService.cs
Labels: documentation, enhancement

#33 Added Github action. Closed #32
  .github/workflows/dotnet.yml
  music-store/Services/Interfaces/IMusicPublisherService.cs
Labels: enhancement, testing

#29 Added receiving a list of new products. Closed #27
  music-store/Models/Entities/VinylRecord.cs
  music-store/Services/Interfaces/IMusicPublisherService.cs
  music-store/Services/Interfaces/IVinylRecordsService.cs
  music-store/Services/VinylRecordsService.cs
Labels: documentation, enhancement

#35 Added method for deleting music bands. Closed #10
  music-store/Services/Interfaces/IMusicBandService.cs
  music-store/Services/MusicBandService.cs
Labels: enhancement
